name: Windows Cloudflare Tunnel
on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Enable RDP Access
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1

      - name: Download LocalXpose or Use Pinggy Web URL
        run: |
          # Pinggy-তে টেনেক্স বা নন-ইন্টারেক্টিভভাবে কানেক্ট করার জন্য -T ফ্ল্যাগ ব্যবহার করা
          ssh -o StrictHostKeyChecking=no -T -R 0:localhost:3389 free.pinggy.io
